tools:
  exceptions: https://tailor-ra.sentry.io/issues/
  logging: https://service.us2.sumologic.com/ui/?appName=tailor&addonId=sumologic#/home
  ci: https://github.com/dcsil/tailor-app/actions

services:
  production: https://tailor-4d71417e9aab.herokuapp.com/

docs:
  getting_started: https://github.com/dcsil/tailor-app
  
commands:
  bootstrap: script/bootstrap
  server: cd tailor-app; cd frontend; npm install; npm run dev
  test: npm test
